/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.scoping;

import org.palladiosimulator.supporting.prolog.scoping.PrologScopeProvider;

public abstract class AbstractProblogScopeProvider extends PrologScopeProvider {
}
