/**
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.tests;

/* @ExtendWith(/* name is null */)
@InjectWith(/* name is null */)
 */public class ProblogParsingTest {
  /* @Inject
   */private /* ParseHelper<Program> */Object parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field ProblogParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
