/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ProblogUiModule extends AbstractProblogUiModule {

	public ProblogUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
