/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.ide;


/**
 * Use this class to register ide components.
 */
public class ProblogIdeModule extends AbstractProblogIdeModule {
}
