/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProblogStandaloneSetup extends ProblogStandaloneSetupGenerated {

	public static void doSetup() {
		new ProblogStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
