/*
 * generated by Xtext 2.24.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.palladiosimulator.supporting.prolog.model.prolog.Program

@ExtendWith(InjectionExtension)
@InjectWith(ProblogInjectorProvider)
class ProblogParsingTest {
	@Inject
	ParseHelper<Program> parseHelper
	
	@Test
	@Disabled
	def void testProbabilisticFact() {
		val result = parseHelper.parse('''
			0.5::heads1.
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
