/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.palladiosimulator.supporting.prolog.validation.PrologValidator;

public abstract class AbstractProblogValidator extends PrologValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://palladiosimulator.org/supporting/prolog/0.1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://palladiosimulator.org/supporting/prolog/probabilistic/0.1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://palladiosimulator.org/supporting/prolog/directives/0.1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://palladiosimulator.org/supporting/prolog/expressions/0.1.0"));
		return result;
	}
}
