/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.supporting.prolog.probabilistic.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.palladiosimulator.supporting.prolog.probabilistic2.ui.internal.Probabilistic2Activator;

public class ProblogUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Probabilistic2Activator.getInstance().getInjector("org.palladiosimulator.supporting.prolog.probabilistic.Problog");
	}

}
